---
- name: Update apt packages
  hosts: all
  tasks:
    - name: Update apt package index
      become: true
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade all packages to the latest version
      become: true
      apt:
        upgrade: full
        autoremove: yes
        autoclean: yes
        purge: true
